### ISSUE TITLE
No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered

### ISSUE THREAD

**Issue by yannduran** [adrianhall/blog-code#1]
When I try to run the aurelia-2 solution I get the following error.

"No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered"

I'm not sure what I need to do to get this working.

**Comment by adrianhall** [comment]
I suspect that the latest upgrade for ASP.NET5 to beta-5 has broken the build.  I'll take a look.
