### ISSUE TITLE
Typescript Errors from Aurelia-2

### ISSUE THREAD

**Issue by cpritchard** [adrianhall/blog-code#2]
Property 'appInsights' does not exist on type 'Window'.	
Property 'appInsights' does not exist on type 'Window'.	
Property 'queue' does not exist on type '{ config: any; }'.	
Property 'src' does not exist on type 'HTMLElement'.	
Property 'cookie' does not exist on type '{ config: any; }'.	
Property 'queue' does not exist on type '{ config: any; }'.	
Type '(config: any, r: any, f: any, e: any, o: any) => any' is not assignable to type 'Window'.
  Property 'animationStartTime' is missing in type '(config: any, r: any, f: any, e: any, o: any) => any'.

**Comment by adrianhall** [comment]
There is some serious problems here.  Unfortunately, I do not keep up to date with the Aurelia code base any longer - this code was an example from a while ago.
