### ISSUE TITLE
How would that work with ASP.NET Core?

### ISSUE THREAD

**Issue by Ponant** [adrianhall/blog-code#3]
Hi @adrianhall , this is not a report of an issue but rather an exchange on how you would approach the problem if you would do ASP.NET Core + Azure Mobile integration of the backend to have it run on Azure. I did not try out yet because I wonder if the code would break due to Microsoft.Azure.Mobile.Server package which seems to be unaware of .Net Core (?).

A side question which I think you are acquainted with is how to deal with User Registration in such site. From An ASP.NET MVC (Core or not) there is a User Identity class persisted to DB whereas in the Azure Tuto's on Auth they define a field MobileServiceUser; thus my question on how can the two talk (to persist the newly registered user from a mobile app to the db and also to avoid code redundancy).

Some guidelines will be greatly appreciated and thanks for your blog!

**Comment by adrianhall** [comment]
You can't do ASP.NET Core and Azure Mobile at this time.  There is an issue on https://github.com/azure/azure-mobile-apps-net-server for ASP.NET core support.

To deal with user registration, you would use custom auth.  This is covered quite extensively in my book and in the standard azure docs.
